language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../All-labs
  - make -j
  - ./Vector/Vector
  - ./VectorTest/VectorTest
  - ./StackTest/StackTest
  - ./QueueTest/QueueTest
  - ./ListTest/ListTest
  - ./ArrListTest/ArrListTest
  - ./MultiStackTest/MultiStackTest
  - ./PolinomTest/PolinomTest
  - ./StackListTest/StackListTest
  - ./PolishTest/PolishTest
notifications:
  email: false
